# Generated by Django 4.2.10 on 2024-04-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mediassist_app', '0002_rename_adhar_number_users_register_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='register_number',
            new_name='trust_register_number',
        ),
    ]
