# Generated by Django 4.2.10 on 2024-04-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mediassist_app', '0003_rename_register_number_users_trust_register_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
