# Generated by Django 4.2.10 on 2024-04-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mediassist_app', '0004_alter_users_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_approval',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
