# Generated by Django 4.2.10 on 2024-04-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mediassist_app', '0006_medicine_request_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_request',
            name='prescription',
            field=models.FileField(default=1, upload_to='pic/'),
            preserve_default=False,
        ),
    ]
