# Generated by Django 4.2.10 on 2024-04-28 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mediassist_app', '0007_alter_medicine_request_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_approval',
            name='paystat',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('exp', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mediassist_app.cash_approval')),
            ],
        ),
    ]
